[target.x86_64-pc-windows-gnu]
linker = "/usr/lib/mingw64-toolchain/bin/x86_64-w64-mingw32-gcc"
ar = "/usr/lib/mingw64-toolchain/bin/x86_64-w64-mingw32-gcc-ar"
rustflags = [
    "-C", "link-arg=-static",
    "-C", "link-arg=-static-libgcc",
    "-C", "panic=abort"
]

[target.x86_64-unknown-linux-gnu]
linker = "gcc"
